"""empty message

Revision ID: 171fad433d5f
Revises: 
Create Date: 2018-11-27 19:28:11.893584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171fad433d5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_username'), 'contact', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_username'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
